version: "3.8"

services:
  analytics-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./analytics.db:/app/analytics.db
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Adicionar banco PostgreSQL para produção
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: analytics
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
# volumes:
#   postgres_data:
